### ISSUE TITLE
[FEAT] Add custom log file location

### ISSUE THREAD

**Issue by rogervn** [linuxserver/docker-homeassistant#102]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Home Assistant added a CLI arg to allow for a different log path. As this is useful on cases that we want to write logs to ramdisk, this seems to be good to expose here as well.

https://github.com/home-assistant/core/pull/9422

### Reason for change

Allow for configurations with ephermeral logging supported already by home assistant

**Comment by barrelltitor** [comment]
I'm not suggesting for this not to be implemented, but docker respects mount order, so until it is implemented you can simply mount the file to your ramdisk
 
```
    volumes:
      - /path/to/config:/config
      - /path/to/ramdisk/home-assistant.log:/config/home-assistant.log
```

**Comment by homerr** [comment]
I think I would rather stick with the suggestion above, it is the best way to deal with this in my opinion as we'd only be telling the file to go elsewhere in the container, that you'd need to pick up with a bind mount regardless.

Good suggestion from @barrelltitor
