### ISSUE TITLE
[BUG] No virtual environment found; run `uv venv` to create an environment

### ISSUE THREAD

**Issue by Ulrar** [linuxserver/docker-homeassistant#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I use the kia uvo integration, and it was working fine until the upgrade to 2024.10.
Now that HA moved to uv instead of pip, it looks like the dependency fails to install.

### Steps To Reproduce

Install the https://github.com/Hyundai-Kia-Connect/kia_uvo integration

### Environment

```markdown
- OS: Kubernetes 1.31.1 (Talos 1.8)
- How docker service was installed: Stateful Set with a PVC using linstor
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
Unable to install package hyundai_kia_connect_api==3.23.6: error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment 
```
```

**Comment by aptalca** [comment]
@Ulrar Can you give this test image a try?
`ghcr.io/linuxserver/lsiodev-homeassistant:2024.10.1-pkg-a41c6583-dev-19bb2522adede948a62aa9d1b64683e366a7656d`

**Comment by Ulrar** [comment]
> @Ulrar Can you give this test image a try? `ghcr.io/linuxserver/lsiodev-homeassistant:2024.10.1-pkg-a41c6583-dev-19bb2522adede948a62aa9d1b64683e366a7656d`

Looks good, the integration loaded fine with that image
