### ISSUE TITLE
Ports are not listed in all applicable README sections

### ISSUE THREAD

**Issue by rocketeerbkw** [linuxserver/docker-homeassistant#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The README should list required port configuration in parameters and examples sections. For example, see the https://github.com/linuxserver/docker-lidarr README.

## Current Behavior
The port for the web UI is only listed under application setup section.

**Comment by tobbenb** [comment]
Please don't open an issue and a PR at the same time. It's enough with the PR.
