### ISSUE TITLE
mysqlclient broken on 2021.09.6

### ISSUE THREAD

**Issue by devin122** [linuxserver/docker-homeassistant#27]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Importing `MySQLdb` results in an import error. Appears as if issue is a result of broken HA wheels (see related #22).

------------------------------

## Expected Behavior
mysqlclient package should be functional.

## Current Behavior
Import error is raised.

## Steps to Reproduce
```
docker run -it --rm --entrypoint bash ghcr.io/linuxserver/homeassistant:version-2021.9.6
root@760d31481f57:/# python3
Python 3.9.5 (default, May 12 2021, 20:44:22)
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
```

## Environment
**OS:** Debian buster
**CPU architecture:** arm64
**How docker service was installed:**  OS repo

## Command used to create docker container (run/create/compose/screenshot)
```
x-tzvolumes:
  - &tzvol "/etc/timezone:/etc/timezone:ro"
  - &timevol "/etc/locatime:/etc/localtime:ro"
x-defaultenv:
  &default-env
  TZ:
  PGID: 1000
  PUID: 1000
services:
  hass:
    image: ghcr.io/linuxserver/homeassistant:version-${HOMEASSISTANT_VERSION}
    container_name: hass
    environment:
      << : *default-env
    volumes:
      - "hass_cfg:/config"
      - *tzvol
      - *timevol
    depends_on:
      - mariadb
      - zwave
    ports:
        - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hassrouter.rule=Host(`hass.lan`)"
      - "traefik.http.routers.hassrouter.tls=true"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"
```

## Docker logs
```
2021-09-20 13:06:57 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup to mysql://homeassistant:quohthaiheeShei8uileingaa4JenoeG@mariadb/homeassistant?charset=utf8: name '_mysql' is not defined (retrying in 3 seconds)
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/MySQLdb/__init__.py", line 18, in <module>
from . import _mysql
ImportError: cannot import name '_mysql' from partially initialized module 'MySQLdb' (most likely due to a circular import) (/usr/lib/python3.9/site-packages/MySQLdb/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 680, in _setup_recorder
self._setup_connection()
File "/usr/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 960, in _setup_connection
self.engine = create_engine(self.db_url, **kwargs)
File "<string>", line 2, in create_engine
File "/usr/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
return fn(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
dbapi = dialect_cls.dbapi(**dbapi_args)
File "/usr/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
return __import__("MySQLdb")
File "/usr/lib/python3.9/site-packages/MySQLdb/__init__.py", line 24, in <module>
version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```

**Comment by aptalca** [comment]
I'm noticing most of the reports about broken python modules are from folks on arm64. Perhaps there is an issue with the HA wheels for that specific arch.

**Comment by devin122** [comment]
This particular issue appears to be caused by the fact that HA uses their own version of python. Standard alpine linux differentiates musl as having a separate abi and as such adjusts the naming of native libraries see (https://github.com/alpinelinux/aports/blob/master/main/python3/bpo-43112.patch)  where as HA's python does not.
Stock alpine:
```
>>> sys.implementation._multiarch
'aarch64-linux-musl'
```
ghcr.io/home-assistant/aarch64-base-python:
```
>>> sys.implementation._multiarch
'aarch64-linux-gnu'
```

Interestingly HA did also distinguish musl and gnu, but they deleted that patch and I can't find any explanation behind the reasoning (https://github.com/home-assistant/docker-base/pull/150). My suspicion is that because they strip the arch from their wheels, they were essentially hitting this same issue in reverse when trying to use musl wheels on their debian images.

Also, just checked and it appears this issue also effects x64

**Comment by aptalca** [comment]
Their wheel repo separates wheels out by not only alpine version, but also by arch: https://wheels.home-assistant.io/
Technically, as long as the c/python version matches, they should work as they should all be musl based.

I see their wheel builder repo, but I don't see any upload functionality there. It's also not clear where the wheels are hosted. I have a feeling they use the builder repo locally and then manually upload to some bucket. Perhaps someone uploaded them to the wrong folder. Since they strip useful info from the wheel names, it would be easy to do that.

**Comment by bigbangus** [comment]
I'm also experiencing this issue. Thanks for your support. What version is safe to roll back to until it's resolved?

**Comment by aptalca** [comment]
I think I'll modify our wheel repo to build HA specific wheels and upload them to the same endpoint so we don't have to rely on theirs that are clearly causing lots of issues.

**Comment by devin122** [comment]
>What version is safe to roll back to until it's resolved?
2021.09.5 has been working for me

**Comment by bigbangus** [comment]
> > What version is safe to roll back to until it's resolved?
> > 2021.09.5 has been working for me

confirmed 2021.9.5 works for me on a mariadb external db_url. thank u
