### ISSUE TITLE
Error occurred loading configuration flow for integration huesyncbox: No module named 'aiohuesyncbox'

### ISSUE THREAD

**Issue by florie1706** [linuxserver/docker-homeassistant#29]
Hi, is there a way to include this module? In the official HA-docker image it is included ;)

**Comment by aptalca** [comment]
It's not listed anywhere in https://github.com/home-assistant/core/blob/dev/requirements_all.txt

What is it for?

**Comment by slinkymanbyday** [comment]
This is from a HACS plugin: [aiohuesyncbox](https://github.com/mvdwetering/huesyncbox)

I'm having the same issue with several of the plugin I install through HACS. my guess is that during startup, homeassistnt tries to install the dependencies for the custom components, but doesn't have the permissions to do so.
