### ISSUE TITLE
Home Assistant fails to connect to camera stream since 2021.9.7-ls42

### ISSUE THREAD

**Issue by Joery** [linuxserver/docker-homeassistant#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Stream to Foscam camera works

## Current Behavior
Stream to Foscam camera doesn't work and an error is given in the logs

## Steps to Reproduce

1. Use 2021.9.7-ls42 or newer
2. Bring up the container via eg. docker-compose up -d
3. Wait for Home Assistant to be fully loaded
4. Camera stream doesn't work / is blank. The PTZ controls are still showing but not working either

## Environment
**OS:** Ubuntu 20.04 Server
**CPU architecture:** x86_64
**How docker service was installed:**
Docker installed via snap during OS install, using docker-compose to setup container

## Command used to create docker container (run/create/compose/screenshot)
https://pastebin.com/gaVScGpG

## Docker logs
`
2021-10-02 23:05:42 ERROR (stream_worker) [libav.tcp] Connection to tcp://172.16.0.81:554?timeout=5000000 failed: Connection refused
`
`
2021-10-02 23:05:42 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://****:****@172.16.0.81:554/videoMain
`

**Comment by drizuid** [comment]
I cant reproduce this, but since the camera is refusing the connection, that would cause issues with accessing the stream.  The deployment method was aged out, so we can't see that either.
