### ISSUE TITLE
Prevent additional /pathtodevice from generating every update?

### ISSUE THREAD

**Issue by rainman369** [linuxserver/docker-homeassistant#35]
I have homeassistant installed on my unRAID machine. I update it every release. In my config, I only have/need one /path to device, - which points to my zigbee controller. 

Every time homeassistant updates, it adds a ton of mandatory path to fields, which I have to manually delete or it prevents homeassistant from starting up (picture attached). 

Any way to prevent this?
![Untitled](https://user-images.githubusercontent.com/61566782/150119991-282c5dd8-7e3c-4928-826a-163ea946faa4.png)

**Comment by tobbenb** [comment]
That is caused by unraid/community applications updating the template. To make it stop, you have to remove the template address under advanced view.

I think if we set this parameter as optional it might not force it back in the template. Since it isn't required, we should probably change it.

**Comment by rainman369** [comment]
> That is caused by unraid/community applications updating the template. To make it stop, you have to remove the template address under advanced view.
> 
> ~I think if we set this parameter as optional it might not force it back in the template. Since it isn't required, we should probably change it.~
> 
> Edit: According to the expert on unraid templates, that will not help, so the solution is to remove the template address.

Thank you for the prompt response - I have attached my advanced view for the container; can you advise what you are referring to as the template address please? 
![update](https://user-images.githubusercontent.com/61566782/150123290-bf90fd65-b0a4-4f17-bb7e-699f986002d0.png)

**Comment by tobbenb** [comment]
Sorry about that. Long time since I changed anything on my unraid server.
You have to enable template authoring in Settings --> Docker. To be able to see this setting, you need to set enable docker to No in the settings page. Then change to Authoring mode and go back to the homeassistant template and delete the TemplateURL address.
I would advice to stop all containers manually before stopping the docker service.

**Comment by rainman369** [comment]
> Sorry about that. Long time since I changed anything on my unraid server. You have to enable template authoring in Settings --> Docker. To be able to see this setting, you need to set enable docker to No in the settings page. Then change to Authoring mode and go back to the homeassistant template and delete the TemplateURL address. I would advice to stop all containers manually before stopping the docker service.

Thanks! I have followed your steps and now see the following (attached) but nothing references TemplateURL specifically, is it one of the ones in the screen grab? Sorry!
![author](https://user-images.githubusercontent.com/61566782/150127950-36944f20-af97-45d5-b301-19ae6a512e6d.png)

**Comment by tobbenb** [comment]
It was there before, so I don't know why it's not there. 
You should ask on the unraid forum why it's happening and how to prevent it.

From our side the template sync is turned off for home-assistant.

**Comment by tobbenb** [comment]
Found it.

https://forums.unraid.net/topic/38619-docker-template-xml-schema/page/2/?tab=comments#comment-825087

**Comment by rainman369** [comment]
I will get over to the forums for further, thanks for narrowing this down

**Comment by rainman369** [comment]
Specific steps to solve this exact problem here for anyone's future reference [https://forums.unraid.net/topic/117686-how-to-editfix-docker-update-pull-command-parameters/](url)
