### ISSUE TITLE
CUPS Integration Support

### ISSUE THREAD

**Issue by Veda82** [linuxserver/docker-homeassistant#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

CUPS integration working correctly.

https://www.home-assistant.io/integrations/cups/

## Current Behavior

CUPS integration doesn't work out of the box due to some libraries missing. See: https://www.home-assistant.io/integrations/cups/

1) First run after adding CUPS integration: the following packages are needed to compile pycups library: python3-dev or python3-devel, libcups2-dev or cups-devel, gcc or equivalent packages. 
2) After the first run, gcc is not needed anymore, since the compiled pycups library is placed into the /config/.local directory.

Adding gcc to the docker image could be overkill, and is needed only for the first run. However, package cups-libs is needed in order for the integration to work.

Moreover, official homeassistant image does indeed include cups-libs package:

https://github.com/home-assistant/docker/blob/master/Dockerfile

## Alternatives Considered

None

**Comment by tobbenb** [comment]
So all that is needed is cups-libs? Or are there more packages needed?

We install home assistant using their requirements, so it's strange the requirements for cups is not in there.

**Comment by aptalca** [comment]
That's a pretty awful docs page. It just tells you to install a bunch of dev packages and leaves it at that?
It looks like it just needs the pycups python package: https://github.com/home-assistant/core/blob/dev/homeassistant/components/cups/manifest.json#L5

> Moreover, official homeassistant image does indeed include cups-libs package:
>
> https://github.com/home-assistant/docker/blob/master/Dockerfile

Where do you see that in that link?

The real issue is that HA for some reason commented out some of the plugin dependencies in their requirements file so they don't get installed in our image: https://github.com/home-assistant/core/blob/dev/requirements_all.txt#L1412
However (I believe) they do have those wheels built in their wheel repo, so their image pulls them from there. But their repo is only compatible with their baseimage and we have to manually add them.

**Comment by Veda82** [comment]
> So all that is needed is cups-libs? Or are there more packages needed?
> 
> We install home assistant using their requirements, so it's strange the requirements for cups is not in there.

In my case, after the first run (which compiles pycups library) only cups-libs is needed.

Without it, Homeassistant logs complains about missing libcups.so.2 library.

**Comment by Veda82** [comment]
> That's a pretty awful docs page. It just tells you to install a bunch of dev packages and leaves it at that? It looks like it just needs the pycups python package: https://github.com/home-assistant/core/blob/dev/homeassistant/components/cups/manifest.json#L5
> 
> > Moreover, official homeassistant image does indeed include cups-libs package:
> > https://github.com/home-assistant/docker/blob/master/Dockerfile
> 
> Where do you see that in that link?

Line 39 to 43:

    apk add --no-cache \
        bluez \
        bluez-deprecated \
        bluez-libs \
        cups-libs \
> 
> The real issue is that HA for some reason commented out some of the plugin dependencies in their requirements file so they don't get installed in our image: https://github.com/home-assistant/core/blob/dev/requirements_all.txt#L1412 However (I believe) they do have those wheels built in their wheel repo, so their image pulls them from there. But their repo is only compatible with their baseimage and we have to manually add them.

**Comment by aptalca** [comment]
> I think that it is not in the requirements because it is indeed not required IF you do not use cups integration.

`requirements_all.txt` contains the deps for all the supported plugins

we'll add both packages to the image
