### ISSUE TITLE
Support MySQL/MariaDB out of the box

### ISSUE THREAD

**Issue by potyt** [linuxserver/docker-homeassistant#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Would be good to be able to use mysql/MariaDB out of the box with this image, at present this doesn't work.

I think the having the mysqlclient package would be enough to support this.

## Current Behavior

using a mysql:// url for recorder results in....
`ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: No module named 'MySQLdb'`

## Alternatives Considered

The homeassistant/home-assistant docker image allows this, and many people do this, but I'd like to use as many of the linuxserver images as possible as they are organised well and have PUID/PGID support.

**Comment by tobbenb** [comment]
Do you know what the mysqlclient package needed is?

**Comment by potyt** [comment]
I believe on the native side, should be libmysqlclient-dev (debian, arch,etc.) and on the python side the package is mysqlclient (https://pypi.org/project/mysqlclient/). The python library uses C-extensions, and links to the native mysql libs, hence performs much better than the pure python version that is floating around.

**Comment by tobbenb** [comment]
Yeah, I found it after reading the home assistant recorder documentation. It's added in the open PR, so should be available when that is merged.
I just added the database li/client packages I saw in the official container, so hopefully there isn't anything missing.

**Comment by tobbenb** [comment]
It should work when the new build is pushed in an hour or so. 
Please test and re-open if it doesn't work.
