### ISSUE TITLE
Container does not recognize network interfaces with enoXvXX naming

### ISSUE THREAD

**Issue by sotiris-bos** [linuxserver/docker-homeassistant#50]
Hello, I am using SR-IOV interfaces passed through to containers by pipework.

The interfaces have names such as: eno1v12

The container does not recognize these interfaces if passed through with their original names. This presents a problem for me as if I restart the container, the interface returns to the host with the name the container gave it, such as eth1 and my passthrough no longer works.

It used to work as intended.

**Comment by j0nnymoe** [comment]
Marked invalid as issue template hasn't been filled out correctly.
