### ISSUE TITLE
Missing modules?

### ISSUE THREAD

**Issue by VederJay** [linuxserver/docker-homeassistant#53]
After the last update, which was automatically installed in my system about 7h ago, my logs are mentioning missing modules and a number of integrations are no longer working. Even a restart of home assistant is blocked due to missing the module "oic".

`2022-07-09 05:27:09 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration invoxia: Unable to import component: No module named 'gps_tracker'
2022-07-09 05:27:51 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration daikin_residential: Unable to import component: No module named 'oic'
2022-07-09 05:28:03 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration huawei_solar: Unable to import component: No module named 'huawei_solar'`

I'm not sure what the root cause is here, as I would expect HA to download the specific dependencies itself (gps_tracker, huawei_solar). But I'm at a loss for the 3rd one, oic, as that is even blocking the restart. 
Timing wise these issues started immediately after the image upgrade so maybe someone here can give me a good next step?

**Comment by VederJay** [comment]
Apparently the issues have to do with the updated Home Assistent version which includes a Python upgrade. Some integrations needed to be updated. 
Restarting the docker when HA didn't let itself be restarted because of the missing oic module also helped once the integrations were updated.

**Comment by onedr0p** [comment]
See https://github.com/home-assistant/core/issues/74700
