### ISSUE TITLE
/etc/services.d/homeassistant/run is no longer marked as executable, breaking s6 read-only root

### ISSUE THREAD

**Issue by Avamander** [linuxserver/docker-homeassistant#54]
*Note: Quite a few linuxserver containers broke like this relatively recently*

## Expected Behavior
The file "/root/etc/services.d/homeassistant/run" is no longer marked executable in the container, configurations utilizing S6_READ_ONLY_ROOT and what mark the root read-only will fail. This is a regression compared to the previous builds.

## Current Behavior
The `./run` file of the homeassistant service is `rw-rw-r--` instead of `rwxr--r--` causing the following error message:
```
homeassistant     | s6-supervise homeassistant (child): fatal: unable to exec run: Permission denied
homeassistant     | s6-supervise homeassistant: warning: unable to spawn ./run - waiting 10 seconds
```
One `chmod` in the container fixes that.

## Steps to Reproduce
Add the snippet provided below to your compose file.

## Similar symptoms or issues: 
* https://github.com/kubeflow/kubeflow/issues/5808#issuecomment-1083558197
* https://github.com/rocker-org/rocker/issues/202
* https://github.com/containers/podman/issues/3803
* https://github.com/Radarr/Radarr/issues/5300
* https://github.com/linuxserver/docker-radarr/issues/113
* https://github.com/just-containers/s6-overlay/issues/158

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** arm64
**How docker service was installed:** Official repos

## Command used to create docker container
```
    read_only: true
    tmpfs:
      - /run:rw,exec
      - /tmp:rw,noexec,nosuid
    environment:
      - "S6_READ_ONLY_ROOT=1"
```

**Comment by Avamander** [comment]
Still relevant.

**Comment by aptalca** [comment]
No, it's not. That file is no longer used in the images.
