### ISSUE TITLE
Psycopg2 missing

### ISSUE THREAD

**Issue by thedanbob** [linuxserver/docker-homeassistant#6]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior
`ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: No module named 'psycopg2' (retrying in 3 seconds) `

Same as #5, the psycopg2 python library needs to be installed to support Postgres out of the box. It’s not clear to me how it’s getting installed in the official image without being in the requirements file.

**Comment by Roxedus** [comment]
They snuck it in to their baseimage (https://github.com/home-assistant/docker/blob/master/requirements.txt), will do a PR
