### ISSUE TITLE
Support for home-assistant/addons

### ISSUE THREAD

**Issue by gsaslis** [linuxserver/docker-homeassistant#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
I would like to use [home-assistant addons](https://github.com/home-assistant/addons) in my home assistant.

## Current Behavior
It doesn't seem to be possible to use addons. 

## Alternatives Considered
I've tried searching (discourse, other gh issues) for how to install these addons in the container image, with little luck... I'm wondering if someone here has already looked into this and found it not to be possible.

**Comment by Roxedus** [comment]
Add-ons are not supported in containers. <https://www.home-assistant.io/installation/#compare-installation-methods>
