### ISSUE TITLE
pyparsing missing

### ISSUE THREAD

**Issue by cliffjao** [linuxserver/docker-homeassistant#63]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
No error

## Current Behavior
Seeing this error in the logs:

`Setup failed for google: Unable to import component: No module named 'pyparsing.unicode'; 'pyparsing' is not a package`

Google Calendar integration doesn't load correctly 

## Steps to Reproduce
1. Upgrade to latest linuxserver/homeassistant:version-2022.11.2
2. Make sure Google Calendar integration is enabled 
3. Start Home Assistant and observe error in logs and Google Calendar integration doesn't load correctly

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:**
OS provided

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up -d homeassistant

## Docker logs
`Setup failed for google: Unable to import component: No module named 'pyparsing.unicode'; 'pyparsing' is not a package`

**Comment by Renegade605** [comment]
Confirmed also on Unraid v6.11.1.

Rolling back to 2022.11.1 fixes the issue. 

Full error log:
```txt
Logger: homeassistant.setup
Source: setup.py:192
First occurred: 19:22:59 (1 occurrences)
Last logged: 19:22:59

Setup failed for google: Unable to import component: No module named 'pyparsing.unicode'; 'pyparsing' is not a package
```

**Comment by aptalca** [comment]
it's in there:
```
# pip list | grep pyparsing
pyparsing                        2.4.7
```

**Comment by aptalca** [comment]
Since neither of you provided enough info (template not filled out either), we would have no idea where to even begin troubleshooting. I do not have that error in my logs.

**Comment by aptalca** [comment]
I need enough info to be able to reproduce it. Docker arguments used, which platform it's running on, what integrations enabled, full logs and most importantly what triggers the error

**Comment by Renegade605** [comment]
Lol. I didn't even notice calendar wasn't mentioned either.

Google Calendar is the integration that malfunctions. Error occurs on startup. No "calendar.*" entities are available. Unraid v6.11.1, docker is included with OS
```txt
docker run
  -d
  --name='homeassistant'
  --net='host'
  -e TZ="America/Denver"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Global-Dynamics"
  -e HOST_CONTAINERNAME="homeassistant"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8123]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png'
  -v '/mnt/user/appdata/homeassistant':'/config':'rw'
  --memory=8G
  --cpu-shares=4096 'ghcr.io/linuxserver/homeassistant'
```

I'm only on my phone atm, so if you need more just say so and I'll get it when I can.

**Comment by Renegade605** [comment]
Certainly sounds like it, when I initially reported it to them they told me it was a container issue not a core issue but they may have been mistaken.

**Comment by Renegade605** [comment]
I've upgraded to 2022.11.3 which should fix the mentioned issue but the problem from this thread persists.

**Comment by aptalca** [comment]
Ugh, it's because HA tells pip to ignore dependency conflicts, and they do have dep conflicts. In this case another package was happy with a lower version of pyparsing so pip did not install the version required for a dependency of the calendar sync package:
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-homeassistant/detail/main/438/pipeline/129#step-143-log-1239
