### ISSUE TITLE
console 

### ISSUE THREAD

**Issue by ArveVM** [linuxserver/docker-homeassistant#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in unRaid; installed docker-container for test-environment a few weeks back.
Added CATT in that container through docker-console of my 'ha-test2'-docker

after an docker upgrade the CATT is gone (expected), but the install now fails

when starting console from ha-test2-docker I get  
root@unraid1:/#    and not 

since unraid1 is name of the server,,, my guess is that there is something wrong

### Expected Behavior

/config #     

### Steps To Reproduce

in unraid
deploy homeassistant-docker
in docker-tab, click icon for new ha-docker
select _console
in console, 
 - check if you got "/config #"
 - type pip3 install catt 
 - and you shold not get warnings on parent directory not owned/writable etc, and error on not running pip as 'root'

I know this worked a few weeks back, but now it is not.
Tried deploying a new container - and same result.

Am not 100% sure it is not some overall config that I've mocked up on unraid,, ,but seems strange as other dockers work with docker-consoles, and new deployed test is not working,,,

### Environment

```markdown
- OS:   unraid 6.15.5
- How docker service was installed:  unraid app-store 


removed config for port8123 (using host network)
removed path to device  (no usb-passthrough)
renamed name of appdata-path to ha-test3  (to avoid naming-conflict with other test-docker)
```

### CPU architecture

x86-64

### Docker creation

```bash
0
```

### Container logs

```bash
0
```

**Comment by thespad** [comment]
Using host network means that your shell will show the host hostname as it's using the host network interface.

You need to provide the specifics of any failure, mostly likely cause is some changed dependency for the package that means it can no longer build with the shipped deps in the container and you'll need to add it/them yourself.
