### ISSUE TITLE
[FEAT] Python Update

### ISSUE THREAD

**Issue by Hooverjc** [linuxserver/docker-homeassistant#73]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

![image](https://github.com/linuxserver/docker-homeassistant/assets/42452872/d306f61f-e35a-4279-8878-5453059d3620)

### Reason for change

Looks like a new requirement coming up in 2 releases (august 2023 release)

**Comment by Roxedus** [comment]
We are already using 3.11. https://github.com/linuxserver/docker-homeassistant/blob/main/package_versions.txt#L1101
