### ISSUE TITLE
Please add PicoTTS

### ISSUE THREAD

**Issue by guix77** [linuxserver/docker-homeassistant#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Add PicoTTS to provide an out-of-the-box local open TTS experience.

## Current Behavior
No PicoTTS available.

## Alternatives Considered
HA's official Docker added Pico TTS:  https://github.com/home-assistant/docker/blob/8440150546a6021a08a7f0417f5b9f9c830bf0cc/Dockerfile#L109

Maybe it could be integrated into this image as well ?

**Comment by tobbenb** [comment]
There isn't any packages available in alpine for it yet for their releases. It's in edge, but not so fond of adding stuff from edge.
Also not so keen on compiling it as it loads our builders.

**Comment by guix77** [comment]
Add a file in /config/custom-cont-init.d, name it with .d extension, like init.d and into it:

```
#!/bin/bash
apk add picotts --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
```
