### ISSUE TITLE
[BUG] pycups integration not working anymore; need to include musl-dev package and pycups==1.9.73

### ISSUE THREAD

**Issue by Veda82** [linuxserver/docker-homeassistant#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Home assistant pycups integration needs pycups==1.9.73 version, but the included version in Alpine docker image is the latest one (2.0.1).

In order to fix the issue, it is possible to use docker-mods, adding musl-dev package and pycups==1.9.73 python package.

However, it would be better to include those in the docker image, in order for the integration to work directly out of the box.

### Expected Behavior

pycups integration working correctly out of the box

### Steps To Reproduce

Use pycups integration in home assistant.

### Environment

```markdown
- OS: TrueNAS
- How docker service was installed: Already included in TrueNAS
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
We can install the correct version of pycups but I do have two questions for the HA team

1. Why are they using an 8 year old version?
2. Why is it commented out in their requirements file? https://github.com/home-assistant/core/blob/367644afe185919c39cdae25609441458307152f/requirements_all.txt#L1616

Oh well

**Comment by Veda82** [comment]
Good questions... It seems that there’s some resistance to make even the tiny change...

https://community.home-assistant.io/t/feature-request-bump-cups-requirement-from-pycups-1-9-73-to-latest-version-2-0-1/581437/11

Don’t know about the manifest, I’ve just asked...
