### ISSUE TITLE
[FEAT] Docker image tags for major releases

### ISSUE THREAD

**Issue by fetzerch** [linuxserver/docker-homeassistant#88]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be nice if there was an image tag with the home assistant major version that gets updated automatically with every minor version release.

E.g. when `2023.11.0` is released, tag `2023.11` is created and points to `2023.11.0`.
Then when `2023.11.1` is released, `2023.11` is updated to point to `2023.11.1` and so on.

### Reason for change

Home assistant usually doesn't do breaking changes in minor releases therefore it's relatively safe to perform minor updates. If there was a docker tag with the major version, people could set their docker-compose/ansible/... scripts to it and automatically get minor updates.

Note that the official home assistant docker image does provide such tags. E.g. [2023.10](https://hub.docker.com/layers/homeassistant/home-assistant/2023.10/images/sha256-6aafaad9679f1ff9b8ac3eed7b1343767f8c78875efb367267aa233f90165ec2?context=explore)

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time#semver-info
