### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by jcheype** [linuxserver/docker-homeassistant#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

An error appear at startup version: `2021.3.4-ls14`

```RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd```

------------------------------

## Expected Behavior
no errors

## Current Behavior
In previous version `2021.3.4-ls13` there is no such error

## Steps to Reproduce
1. start the container

## Environment
**OS:** linux debian
**CPU architecture:** x86_64

**Comment by tobbenb** [comment]
Closing this as not enough info was added in the issue template.
