### ISSUE TITLE
[BUG] no default login/pwd provided

### ISSUE THREAD

**Issue by icf20** [linuxserver/docker-homeassistant#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![imagen](https://github.com/linuxserver/docker-homeassistant/assets/17784575/54a81e08-389e-42c2-bd69-6955c0dcb54a)

### Expected Behavior

a way to set admin and password or given a admin/admin

### Steps To Reproduce

install the via docker 

### Environment

```markdown
- OS:debian
- How docker service was installed: apt
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
    ports:
      - 8123:8123 #optional
    devices:
      - /path/to/device:/path/to/device #optional
    restart: unless-stopped
```

### Container logs

```bash
[custom-init] No custom files found, skipping...

[ls.io-init] done.

2023-12-01 00:37:55.948 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from xx. Requested URL: '/auth/login_flow/e7ce19b8efcdd398e8211774
```

**Comment by j0nnymoe** [comment]
None is needed. It's done via the setup wizard. You likely have pointed it to an existing install.

**Comment by havedill** [comment]
I'm seeing this same thing. Brand new docker container on Unraid goes straight to login screen. No setup wizard is prompted.
