### ISSUE TITLE
[FEAT] Update python to 3.12

### ISSUE THREAD

**Issue by florie1706** [linuxserver/docker-homeassistant#95]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Could you please be so kind to update python to the latest version :) Thanks in advance

### Reason for change

As of Home Assistant 2024.2 I get an warning for this:

`2024-02-01 09:35:46.392 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.11.6 is deprecated and will be removed in Home Assistant 2024.4; Please upgrade Python to 3.12`

**Comment by aptalca** [comment]
> As of Home Assistant 2024.2 I get an warning for this:

Are you sure you're using our image? We don't have a build for 2024.2 as it has not been released to stable yet. Latest we pushed is 2024.1.6

**Comment by florie1706** [comment]
I use your git to build it with the beta.

**Comment by aptalca** [comment]
@florie1706 
I have a test build of HA with py3.12. When you get a chance, can you test and let us know if you encounter any issues?
`lsiodev/homeassistant:2024.2.0-py312`
Thanks
It's built off of this branch: https://github.com/linuxserver/docker-homeassistant/tree/py312

**Comment by florie1706** [comment]
Hi @aptalca thanks for test build. Seems to work. Core integrations and some of my custom integrations worked. HA is running, no more warning (of course). But I needed to revert back because a couple of my custom integrations stopped working. I think they have to be upgraded to py3.12 as well.  I check with the non working to get them run :)

**Comment by n3rdcoach** [comment]
Hi, same Problem here:  2024.2.0 Frontend 20240207.0   

original error message (in german):
Dies funktioniert nicht mehr in Version 2024.4. Bitte behebe dies vor dem Upgrade.
Die Unterstützung für die Ausführung von Home Assistant in der aktuell verwendeten Python-Version 3.11.6 ist veraltet und wird in Home Assistant 2024.4 entfernt. Bitte aktualisiere Python auf 3.12, um zu verhindern, dass deine Home Assistant-Instanz beschädigt wird.


build_version | Linuxserver.io version:- 2024.2.0-ls229 Build-date:- 2024-02-07T21:02:11+00:00

**Comment by florie1706** [comment]
Everybody will have this message because everybody uses the same image ;) You could also try the test build from @aptalca  two messages prior yours or wait until python 3.12 is officially in the release images here.

**Comment by vw-kombi** [comment]
I use unraid, so I have no option but to just install from the community app store - which now does not work.
What are my options, if any ?

**Comment by j0nnymoe** [comment]
Currently you need to roll back to the previous version and not update.

**Comment by vw-kombi** [comment]
> Currently you need to roll back to the previous version and not update.

Well thats a pain.  Just restored - back to yesterday morning backups........ And now it starts - but no sensors are working at all - all offline..... I only moved to container from my VM 3 weeks ago and was stable on VM for years.  
Will look ino it tomorrow as its too late now.

**Comment by vw-kombi** [comment]
Actually - my dashboard was like that - there are no actual sensors there are at all after restore!!!!!!
I have a config somewhere saved......

**Comment by florie1706** [comment]
But are your problems really related to my feature request to have python 3.12 in an upcoming release image?

**Comment by vw-kombi** [comment]
> But are your problems really related to my feature request to have python 3.12 in an upcoming release image?

Prob not - I will have to work through the restores and manual copy - I am on holiday in bali - shold never have hit that update button while I am still 3 weeks away!

**Comment by Beimer0815** [comment]
Hi, also got the warning but I'm confused people already got issues cause the warningist just saying its going to break at version 2024.4. Anyhow I'm happy that die python upgrade o 3.12 got adressed cause like others here I'm also using unraid for some small instances of HA and I don't want to switch to anywhere else, Thanks.

**Comment by redpixy** [comment]
I currently using the 3.12 branch. it seems everything is working fine. 
I did notice my HA stop restarting itself randomly after 3 - 4 hrs after using the 3.12 branch.

**Comment by florie1706** [comment]
@aptalca I used your test build from the beginning and with HA 2024.2.1 I built my own images which runs also very well. Nothing to report. Thanks again for your effort.
