### ISSUE TITLE
Ignore - I have other issues that may relate to this -Updated and broken.  Have backups, so installed new - still issues 

### ISSUE THREAD

**Issue by vw-kombi** [linuxserver/docker-homeassistant#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Top of log in container shows tis :

Error: Command '['/config/lsiopy/bin/python3.11', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
s6-applyuidgid: fatal: unable to exec /config/lsiopy/bin/pip: Socket not connected
find: /config: Socket not connected
exec: fatal: unable to exec bash: Socket not connected
s6-rc: warning: unable to start service init-usb-homeassistant: command exited 126

### Expected Behavior

new container should install and work.

When I updated, there were tons of errors - so a fresh was done - but that also does not work

### Steps To Reproduce

Trtied updating - got lots of errors on startup
so deleted container and appdata\homeassistant
installed as fresh - and still wont start.

### Environment

```markdown
- OS: Unraid
- How docker service was installed: from unraid community app store
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid so this is done from the app store automatically
```

### Container logs

```bash
Error: Command '['/config/lsiopy/bin/python3.11', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
s6-applyuidgid: fatal: unable to exec /config/lsiopy/bin/pip: Socket not connected
find: /config: Socket not connected
exec: fatal: unable to exec bash: Socket not connected
s6-rc: warning: unable to start service init-usb-homeassistant: command exited 126
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

Creating venv in /config/lsiopy for runtime use
Updating pip to HA supported version
Setting permissions
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****

** Press ANY KEY to close this window **
```

**Comment by j0nnymoe** [comment]
Related issue https://github.com/linuxserver/docker-homeassistant/issues/95

**Comment by vw-kombi** [comment]
close this - I have other issues on the server that likely relate - other containers are stopping.
